// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace ReviewerRecommender.Models.GitLab
{

    public class Change
    {

        [JsonProperty("old_path")]
        public string OldPath { get; set; }

        [JsonProperty("new_path")]
        public string NewPath { get; set; }

        [JsonProperty("a_mode")]
        public string AMode { get; set; }

        [JsonProperty("b_mode")]
        public string BMode { get; set; }

        [JsonProperty("diff")]
        public string Diff { get; set; }

        [JsonProperty("new_file")]
        public bool NewFile { get; set; }

        [JsonProperty("renamed_file")]
        public bool RenamedFile { get; set; }

        [JsonProperty("deleted_file")]
        public bool DeletedFile { get; set; }
    }

}
