// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace ReviewerRecommender.Models.GitLab
{

    public class Commit
    {

        [JsonProperty("id")]
        public string Id { get; set; }

        [JsonProperty("message")]
        public string Message { get; set; }

        [JsonProperty("timestamp")]
        public string Timestamp { get; set; }

        [JsonProperty("url")]
        public string Url { get; set; }

        [JsonProperty("author")]
        public GitLabUser Author { get; set; }

        [JsonProperty("added")]
        public string[] Added { get; set; }

        [JsonProperty("modified")]
        public string[] Modified { get; set; }

        [JsonProperty("removed")]
        public string[] Removed { get; set; }
    }

}
