// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace ReviewerRecommender.Models.GitLab
{
    public partial class MergeRequest
    {
        [JsonProperty("id")]
        public int Id { get; set; }

        [JsonProperty("iid")]
        public int Iid { get; set; }

        [JsonProperty("target_branch")]
        public string TargetBranch { get; set; }

        [JsonProperty("source_branch")]
        public string SourceBranch { get; set; }

        [JsonProperty("project_id")]
        public int ProjectId { get; set; }

        [JsonProperty("title")]
        public string Title { get; set; }

        [JsonProperty("state")]
        public string State { get; set; }

        [JsonProperty("upvotes")]
        public int Upvotes { get; set; }

        [JsonProperty("downvotes")]
        public int Downvotes { get; set; }

        [JsonProperty("author")]
        public GitLabUser Author { get; set; }

        [JsonProperty("assignee")]
        public GitLabUser Assignee { get; set; }

        [JsonProperty("source_project_id")]
        public string SourceProjectId { get; set; }

        [JsonProperty("target_project_id")]
        public string TargetProjectId { get; set; }

        [JsonProperty("labels")]
        public string[] Labels { get; set; }

        [JsonProperty("description")]
        public string Description { get; set; }

        [JsonProperty("work_in_progress")]
        public bool WorkInProgress { get; set; }

        [JsonProperty("milestone")]
        public Milestone Milestone { get; set; }

        [JsonProperty("merge_when_build_succeeds")]
        public bool MergeWhenBuildSucceeds { get; set; }

        [JsonProperty("merge_status")]
        public string MergeStatus { get; set; }
    }

}
