// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace ReviewerRecommender.Models.GitLab
{

    public class Repository
    {

        [JsonProperty("name")]
        public string Name { get; set; }

        [JsonProperty("url")]
        public string Url { get; set; }

        [JsonProperty("description")]
        public string Description { get; set; }

        [JsonProperty("homepage")]
        public string Homepage { get; set; }

        [JsonProperty("git_http_url")]
        public string GitHttpUrl { get; set; }

        [JsonProperty("git_ssh_url")]
        public string GitSshUrl { get; set; }

        [JsonProperty("visibility_level")]
        public int VisibilityLevel { get; set; }
    }

}
