//------------------------------------------------------------------------------
// <auto-generated>
//    Dieser Code wurde aus einer Vorlage generiert.
//
//    Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten Ihrer Anwendung.
//    Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExpertiseDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class ActualReviewer
    {
        public int ActualReviewerId { get; set; }
        public int ActivityId { get; set; }
        public string Reviewer { get; set; }
        public int RepositoryId { get; set; }
        public int BugId { get; set; }
    
        public virtual Repository Repository { get; set; }
        public virtual Bug Bug { get; set; }
    }
}
