//------------------------------------------------------------------------------
// <auto-generated>
//    Dieser Code wurde aus einer Vorlage generiert.
//
//    Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten Ihrer Anwendung.
//    Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExpertiseDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Algorithm
    {
        public Algorithm()
        {
            this.DeveloperExpertiseValues = new HashSet<DeveloperExpertiseValue>();
            this.RepositoryAlgorithmRunStatus = new HashSet<RepositoryAlgorithmRunStatus>();
        }
    
        public int AlgorithmId { get; set; }
        public string Name { get; set; }
        public System.Guid GUID { get; set; }
    
        public virtual ICollection<DeveloperExpertiseValue> DeveloperExpertiseValues { get; set; }
        public virtual ICollection<RepositoryAlgorithmRunStatus> RepositoryAlgorithmRunStatus { get; set; }
    }
}
