//------------------------------------------------------------------------------
// <auto-generated>
//    Dieser Code wurde aus einer Vorlage generiert.
//
//    Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten Ihrer Anwendung.
//    Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExpertiseDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Artifact
    {
        public Artifact()
        {
            this.ModificationCount = 0;
            this.DeveloperExpertises = new HashSet<DeveloperExpertise>();
            this.ChildArtifacts = new HashSet<Artifact>();
            this.Bugs = new HashSet<Bug>();
        }
    
        public int ArtifactId { get; set; }
        public int ArtifactTypeId { get; set; }
        public string Name { get; set; }
        public int RepositoryId { get; set; }
        public Nullable<int> ParentArtifactId { get; set; }
        public int ModificationCount { get; set; }
    
        public virtual ArtifactType ArtifactType { get; set; }
        public virtual Repository Repository { get; set; }
        public virtual ICollection<DeveloperExpertise> DeveloperExpertises { get; set; }
        public virtual ICollection<Artifact> ChildArtifacts { get; set; }
        public virtual Artifact ParentArtifact { get; set; }
        public virtual ICollection<Bug> Bugs { get; set; }
    }
}
