
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace ExpertiseExplorer.ExpertiseDB
{

using System;
    using System.Collections.Generic;
    
public partial class Artifact
{

    public Artifact()
    {

        this.ModificationCount = 0;

        this.DeveloperExpertises = new HashSet<DeveloperExpertise>();

        this.ChildArtifacts = new HashSet<Artifact>();

        this.Bugs = new HashSet<Bug>();

    }


    public int ArtifactId { get; set; }

    public int ArtifactTypeId { get; set; }

    public string Name { get; set; }

    public int RepositoryId { get; set; }

    public Nullable<int> ParentArtifactId { get; set; }

    public int ModificationCount { get; set; }



    public virtual ArtifactType ArtifactType { get; set; }

    public virtual Repository Repository { get; set; }

    public virtual ICollection<DeveloperExpertise> DeveloperExpertises { get; set; }

    public virtual ICollection<Artifact> ChildArtifacts { get; set; }

    public virtual Artifact ParentArtifact { get; set; }

    public virtual ICollection<Bug> Bugs { get; set; }

}

}
