
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace ExpertiseDB
{

using System;
    using System.Collections.Generic;
    
public partial class Bug
{

    public Bug()
    {

        this.Artifacts = new HashSet<Artifact>();

        this.ActualReviewers = new HashSet<ActualReviewer>();

        this.ComputedReviewers = new HashSet<ComputedReviewer>();

    }


    public int BugId { get; set; }

    public string ChangeId { get; set; }

    public int RepositoryId { get; set; }



    public virtual ICollection<Artifact> Artifacts { get; set; }

    public virtual ICollection<ActualReviewer> ActualReviewers { get; set; }

    public virtual ICollection<ComputedReviewer> ComputedReviewers { get; set; }

    public virtual Repository Repository { get; set; }

}

}
