//------------------------------------------------------------------------------
// <auto-generated>
//    Dieser Code wurde aus einer Vorlage generiert.
//
//    Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten Ihrer Anwendung.
//    Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExpertiseDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bug
    {
        public Bug()
        {
            this.Artifacts = new HashSet<Artifact>();
            this.ActualReviewers = new HashSet<ActualReviewer>();
            this.ComputedReviewers = new HashSet<ComputedReviewer>();
        }
    
        public int BugId { get; set; }
        public string ChangeId { get; set; }
    
        public virtual ICollection<Artifact> Artifacts { get; set; }
        public virtual ICollection<ActualReviewer> ActualReviewers { get; set; }
        public virtual ICollection<ComputedReviewer> ComputedReviewers { get; set; }
    }
}
