//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExpertiseDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class ComputedReviewer
    {
        public int ComputedReviewerId { get; set; }
        public string Expert1 { get; set; }
        public double Expert1Value { get; set; }
        public string Expert2 { get; set; }
        public double Expert2Value { get; set; }
        public string Expert3 { get; set; }
        public double Expert3Value { get; set; }
        public string Expert4 { get; set; }
        public double Expert4Value { get; set; }
        public string Expert5 { get; set; }
        public double Expert5Value { get; set; }
        public int ActualReviewerId { get; set; }
        public int AlgorithmId { get; set; }
    
        public virtual ActualReviewer ActualReviewer { get; set; }
    }
}
