
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace ExpertiseExplorer.ExpertiseDB
{

using System;
    using System.Collections.Generic;
    
public partial class ComputedReviewer
{

    public int ComputedReviewerId { get; set; }

    public double Expert1Value { get; set; }

    public double Expert2Value { get; set; }

    public double Expert3Value { get; set; }

    public double Expert4Value { get; set; }

    public double Expert5Value { get; set; }

    public int AlgorithmId { get; set; }

    public int BugId { get; set; }

    public Nullable<int> Expert1Id { get; set; }

    public Nullable<int> Expert2Id { get; set; }

    public Nullable<int> Expert3Id { get; set; }

    public Nullable<int> Expert4Id { get; set; }

    public Nullable<int> Expert5Id { get; set; }



    public virtual Bug Bug { get; set; }

    public virtual Developer Expert1 { get; set; }

    public virtual Developer Expert2 { get; set; }

    public virtual Developer Expert3 { get; set; }

    public virtual Developer Expert4 { get; set; }

    public virtual Developer Expert5 { get; set; }

}

}
