//------------------------------------------------------------------------------
// <auto-generated>
//    Dieser Code wurde aus einer Vorlage generiert.
//
//    Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten Ihrer Anwendung.
//    Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExpertiseDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class ComputedReviewer
    {
        public int ComputedReviewerId { get; set; }
        public string Expert1 { get; set; }
        public double Expert1Value { get; set; }
        public string Expert2 { get; set; }
        public double Expert2Value { get; set; }
        public string Expert3 { get; set; }
        public double Expert3Value { get; set; }
        public string Expert4 { get; set; }
        public double Expert4Value { get; set; }
        public string Expert5 { get; set; }
        public double Expert5Value { get; set; }
        public int ActualReviewerId { get; set; }
        public int AlgorithmId { get; set; }
        public int BugId { get; set; }
    
        public virtual Bug Bug { get; set; }
    }
}
