
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace ExpertiseExplorer.ExpertiseDB
{

using System;
    using System.Collections.Generic;
    
public partial class Developer
{

    public Developer()
    {

        this.DeveloperExpertises = new HashSet<DeveloperExpertise>();

    }


    public int DeveloperId { get; set; }

    public string Name { get; set; }

    public int RepositoryId { get; set; }



    public virtual Repository Repository { get; set; }

    public virtual ICollection<DeveloperExpertise> DeveloperExpertises { get; set; }

}

}
