//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExpertiseDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class FileRevision
    {
        public FileRevision()
        {
            this.IsNew = false;
            this.LinesAdded = 0;
            this.LinesDeleted = 0;
        }
    
        public int FileRevisionId { get; set; }
        public bool IsNew { get; set; }
        public int LinesAdded { get; set; }
        public int LinesDeleted { get; set; }
        public string Diff { get; set; }
        public int RevisionId { get; set; }
        public int FilenameId { get; set; }
        public int SourceRepositoryId { get; set; }
    
        public virtual Revision Revision { get; set; }
        public virtual Filename Filename { get; set; }
        public virtual SourceRepository SourceRepository { get; set; }
    }
}
