//------------------------------------------------------------------------------
// <auto-generated>
//    Dieser Code wurde aus einer Vorlage generiert.
//
//    Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten Ihrer Anwendung.
//    Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExpertiseDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Repository
    {
        public Repository()
        {
            this.Developers = new HashSet<Developer>();
            this.Artifacts = new HashSet<Artifact>();
            this.ActualReviewers = new HashSet<ActualReviewer>();
            this.RepositoryAlgorithmRunStatus = new HashSet<RepositoryAlgorithmRunStatus>();
        }
    
        public int RepositoryId { get; set; }
        public string Name { get; set; }
        public string SourceURL { get; set; }
        public Nullable<System.DateTime> LastUpdate { get; set; }
    
        public virtual ICollection<Developer> Developers { get; set; }
        public virtual ICollection<Artifact> Artifacts { get; set; }
        public virtual ICollection<ActualReviewer> ActualReviewers { get; set; }
        public virtual ICollection<RepositoryAlgorithmRunStatus> RepositoryAlgorithmRunStatus { get; set; }
    }
}
