//------------------------------------------------------------------------------
// <auto-generated>
//    Dieser Code wurde aus einer Vorlage generiert.
//
//    Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten Ihrer Anwendung.
//    Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExpertiseDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class RepositoryAlgorithmRunStatus
    {
        public int RepositoryRepositoryId { get; set; }
        public int AlgorithmAlgorithmId { get; set; }
        public System.DateTime RunUntil { get; set; }
    
        public virtual Repository Repository { get; set; }
        public virtual Algorithm Algorithm { get; set; }
    }
}
