
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace ExpertiseExplorer.ExpertiseDB
{

using System;
    using System.Collections.Generic;
    
public partial class RepositoryAlgorithmRunStatus
{

    public int RepositoryId { get; set; }

    public int AlgorithmId { get; set; }

    public System.DateTime RunUntil { get; set; }



    public virtual Repository Repository { get; set; }

    public virtual Algorithm Algorithm { get; set; }

}

}
