//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExpertiseDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Revision
    {
        public Revision()
        {
            this.Files = new HashSet<FileRevision>();
        }
    
        public int RevisionId { get; set; }
        public string User { get; set; }
        public string Tag { get; set; }
        public string Parent { get; set; }
        public string ID { get; set; }
        public string Description { get; set; }
        public System.DateTime Time { get; set; }
        public int SourceRepositoryId { get; set; }
    
        public virtual SourceRepository SourceRepository { get; set; }
        public virtual ICollection<FileRevision> Files { get; set; }
    }
}
